version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      docker: 20.10.15
  pre_build:
    commands:
      - echo In the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - java -version
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn clean install
      - mv target/usermanagement-0.0.1-SNAPSHOT.jar app.jar
artifacts:
  files:
    - app.jar
    - .ebextensions/**/*