version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      docker: 20
  pre_build:
    commands:
      - echo In the pre_build phase...
      - echo Logging in to Amazon ECR.....
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=979213071888.dkr.ecr.eu-west-1.amazonaws.com/app-ng-ecr
      - git config --global user.name "nitin ghosh"
      - git config --global user.email "nitin.ghosh1990@gmail.com"
      - git remote set-url origin https://github.com/NitinG11/e2e-microservices-devops.git
      - ID=$(git log --format="%H" -n 1 | tail -c 7)
      - echo $ID
      - IMAGE_TAG=1.0.0
  build:
    commands:
      - echo Build started on `date`
      - java -version
      - mvn test
      - echo Build completed on `date`
      - mvn clean install
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - mv target/usermanagement-0.0.1-SNAPSHOT.jar app.jar
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"usermgmt","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - app.jar
    - .ebextensions/**/*
    - imagedefinitions.json