server:
  port: 8081

spring:
  application:
    name: user-management

  datasource:
    url: jdbc:mysql://${AWS_RDS_HOSTNAME:172.17.0.4}:${AWS_RDS_PORT:3306}/${AWS_RDS_DB_NAME:usermanagement}?allowPublicKeyRetrieval=true&useSSL=false
    #driverClassName: org.h2.Driver
    username: ${AWS_RDS_USERNAME:root}
    password: ${AWS_RDS_PASSWORD:passw0rd11}

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: none
    generate-ddl: true

  h2:
    console:
      enabled: true


  sql:
    init:
      mode: always
  liquibase:
    change-log: "db/changelog/master-changelog.yaml"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html



